insert into "public"."discussion" (discussion_id, course_id, title, post_date) values (1, 1, 'Basic Industries', '2020-01-21');
insert into "public"."discussion" (discussion_id, course_id, title, post_date) values (2, 2, 'Health Care', '2021-09-21');
insert into "public"."discussion" (discussion_id, course_id, title, post_date) values (3, 3, 'Health Care', '2022-04-23');
insert into "public"."discussion" (discussion_id, course_id, title, post_date) values (4, 4, 'Miscellaneous', '2023-06-11');
insert into "public"."discussion" (discussion_id, course_id, title, post_date) values (5, 5, 'Technology', '2023-02-10');
insert into "public"."discussion" (discussion_id, course_id, title, post_date) values (6, 6, 'Technology', '2020-02-25');
insert into "public"."discussion" (discussion_id, course_id, title, post_date) values (7, 7, 'Energy', '2023-10-02');
insert into "public"."discussion" (discussion_id, course_id, title, post_date) values (8, 8, 'Capital Goods', '2020-10-16');
insert into "public"."discussion" (discussion_id, course_id, title, post_date) values (9, 9, 'Consumer Non-Durables', '2022-12-07');
insert into "public"."discussion" (discussion_id, course_id, title, post_date) values (10, 10, 'Health Care', '2022-01-04');
insert into "public"."discussion" (discussion_id, course_id, title, post_date) values (11, 11, 'Technology', '2020-03-26');
insert into "public"."discussion" (discussion_id, course_id, title, post_date) values (12, 12, 'Capital Goods', '2021-09-19');
insert into "public"."discussion" (discussion_id, course_id, title, post_date) values (13, 13, 'Finance', '2019-12-27');
insert into "public"."discussion" (discussion_id, course_id, title, post_date) values (14, 14, 'Energy', '2021-05-15');
insert into "public"."discussion" (discussion_id, course_id, title, post_date) values (15, 15, 'Public Utilities', '2022-09-04');
