insert into "public"."message" (message_id, discussion_id, student_id, timestamp, message) values (1, 1, 82, '2023-06-19 06:52:10', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.');
insert into "public"."message" (message_id, discussion_id, student_id, timestamp, message) values (2, 2, 85, '2023-09-17 09:53:14', 'Praesent blandit lacinia erat.');
insert into "public"."message" (message_id, discussion_id, student_id, timestamp, message) values (3, 3, 58, '2023-09-18 01:54:11', 'Curabitur at ipsum ac tellus semper interdum.');
insert into "public"."message" (message_id, discussion_id, student_id, timestamp, message) values (4, 4, 91, '2023-04-11 08:52:18', 'Etiam vel augue. Vestibulum rutrum rutrum neque.');
insert into "public"."message" (message_id, discussion_id, student_id, timestamp, message) values (5, 5, 61, '2023-01-15 02:56:13', 'Suspendisse accumsan tortor quis turpis.');
insert into "public"."message" (message_id, discussion_id, student_id, timestamp, message) values (6, 6, 93, '2023-05-13 08:52:18', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.');
insert into "public"."message" (message_id, discussion_id, student_id, timestamp, message) values (7, 7, 95, '2023-06-10 09:51:10', 'Sed sagittis.');
insert into "public"."message" (message_id, discussion_id, student_id, timestamp, message) values (8, 8, 96, '2023-08-10 05:50:19', 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.');
insert into "public"."message" (message_id, discussion_id, student_id, timestamp, message) values (9, 9, 70, '2023-01-15 09:55:14', 'Vivamus vel nulla eget eros elementum pellentesque.');
insert into "public"."message" (message_id, discussion_id, student_id, timestamp, message) values (10, 10, 98, '2023-08-12 05:53:18', 'Integer ac neque.');
insert into "public"."message" (message_id, discussion_id, student_id, timestamp, message) values (11, 11, 99, '2023-05-14 09:57:16', 'In hac habitasse platea dictumst.');
insert into "public"."message" (message_id, discussion_id, student_id, timestamp, message) values (12, 12, 100, '2023-01-19 05:52:17', 'Phasellus in felis. Donec semper sapien a libero.');
insert into "public"."message" (message_id, discussion_id, student_id, timestamp, message) values (13, 13, 101, '2023-07-14 03:57:14', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.');
insert into "public"."message" (message_id, discussion_id, student_id, timestamp, message) values (14, 14, 77, '2023-03-11 05:55:16', 'Vivamus vel nulla eget eros elementum pellentesque.');
insert into "public"."message" (message_id, discussion_id, student_id, timestamp, message) values (15, 15, 80, '2023-07-13 08:53:13', 'Integer ac leo. Pellentesque ultrices mattis odio.');
insert into "public"."message" (message_id, discussion_id, student_id, timestamp, message) values (16, 1, 52, '2023-03-15 06:52:14', 'Suspendisse potenti. Nullam porttitor lacus at turpis.');
insert into "public"."message" (message_id, discussion_id, student_id, timestamp, message) values (17, 2, 55, '2023-07-16 02:51:17', 'Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.');
insert into "public"."message" (message_id, discussion_id, student_id, timestamp, message) values (18, 3, 33, '2023-04-15 00:50:17', 'Nulla tellus. In sagittis dui vel nisl.');
insert into "public"."message" (message_id, discussion_id, student_id, timestamp, message) values (19, 4, 60, '2023-05-15 09:57:17', 'Nunc rhoncus dui vel sem. Sed sagittis.');
insert into "public"."message" (message_id, discussion_id, student_id, timestamp, message) values (20, 5, 92, '2023-05-13 08:53:12', 'In hac habitasse platea dictumst.');
insert into "public"."message" (message_id, discussion_id, student_id, timestamp, message) values (21, 6, 62, '2023-01-18 01:50:10', 'Suspendisse accumsan tortor quis turpis.');
insert into "public"."message" (message_id, discussion_id, student_id, timestamp, message) values (22, 7, 66, '2023-05-15 08:54:14', 'Duis bibendum.');
insert into "public"."message" (message_id, discussion_id, student_id, timestamp, message) values (23, 8, 69, '2023-02-13 07:58:16', 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.');
insert into "public"."message" (message_id, discussion_id, student_id, timestamp, message) values (24, 9, 43, '2023-09-19 00:52:17', 'Praesent lectus.');
insert into "public"."message" (message_id, discussion_id, student_id, timestamp, message) values (25, 10, 71, '2023-02-19 03:58:13', 'Nulla mollis molestie lorem.');
insert into "public"."message" (message_id, discussion_id, student_id, timestamp, message) values (26, 11, 72, '2023-08-16 05:56:13', 'In congue.');
insert into "public"."message" (message_id, discussion_id, student_id, timestamp, message) values (27, 12, 73, '2023-01-15 06:57:16', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.');
insert into "public"."message" (message_id, discussion_id, student_id, timestamp, message) values (28, 13, 75, '2023-04-14 04:51:17', 'Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.');
insert into "public"."message" (message_id, discussion_id, student_id, timestamp, message) values (29, 14, 77, '2023-05-17 02:57:13', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into "public"."message" (message_id, discussion_id, student_id, timestamp, message) values (30, 15, 51, '2023-05-18 01:52:12', 'Proin eu mi. Nulla ac enim.');
