insert into "public"."rating" (rating_id, course_id, student_id, rating, comment) values (1, 1, 3, 1, 'Aliquam non mauris. Morbi non lectus.');
insert into "public"."rating" (rating_id, course_id, student_id, rating, comment) values (2, 2, 32, 2, 'Donec semper sapien a libero. Nam dui.');
insert into "public"."rating" (rating_id, course_id, student_id, rating, comment) values (3, 3, 58, 6, 'Phasellus sit amet erat. Nulla tempus.');
insert into "public"."rating" (rating_id, course_id, student_id, rating, comment) values (4, 4, 11, 4, 'In congue. Etiam justo.');
insert into "public"."rating" (rating_id, course_id, student_id, rating, comment) values (5, 5, 61, 5, 'Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.');
insert into "public"."rating" (rating_id, course_id, student_id, rating, comment) values (6, 6, 14, 4, 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.');
insert into "public"."rating" (rating_id, course_id, student_id, rating, comment) values (7, 7, 95, 2, 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.');
insert into "public"."rating" (rating_id, course_id, student_id, rating, comment) values (8, 8, 17, 0, 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.');
insert into "public"."rating" (rating_id, course_id, student_id, rating, comment) values (9, 9, 43, 4, 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.');
insert into "public"."rating" (rating_id, course_id, student_id, rating, comment) values (10, 10, 21, 10, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.');
insert into "public"."rating" (rating_id, course_id, student_id, rating, comment) values (11, 11, 99, 2, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.');
insert into "public"."rating" (rating_id, course_id, student_id, rating, comment) values (12, 12, 48, 9, 'Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.');
insert into "public"."rating" (rating_id, course_id, student_id, rating, comment) values (13, 13, 49, 5, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.');
insert into "public"."rating" (rating_id, course_id, student_id, rating, comment) values (14, 14, 77, 6, 'Pellentesque at nulla. Suspendisse potenti.');
insert into "public"."rating" (rating_id, course_id, student_id, rating, comment) values (15, 15, 51, 10, 'Integer ac leo. Pellentesque ultrices mattis odio.');
